### ISSUE TITLE
[询问] 关于多区域和多轮对话的咨询

### ISSUE THREAD

**Issue by hhaAndroid** [dongyh20/Chain-of-Spot#1]
作者好，非常感谢你开源的很好的工作，我看完论文有3个疑问

1. 我看你做的都是关注于单轮对话场景，COS 是否有可能实现在多轮对话场景下，我感觉步骤会比较繁琐，也就是这个做法的扩展性咋样？
2.  COS 评测应该都是客观指标且单轮对话吧，你们是否有评测过多轮对话？
3. 如果某个问题涉及到多个区域，例如图片问的是 a and b 这种，此时单区域估计会有问题，这是否也是一个扩展性相关的问题？

我还发现你们论文提的 good case 都是非常符合你们场景的例子，是否应该也贴一些 bad case(因为我感觉会有一些 case 不是很适用 COS)，这样才可以让用户更全面的评估算法呢？

以上只是我个人的浅显看法，不一定对，欢迎讨论。

**Comment by dongyh20** [comment]
Thank you for interest in our research. We are pleased to discuss these questions one by one.

- **How to extend our approach to multiple rounds of conversations?** 

As our method can directly identify the ROI based on a specific question, it is easy to transfer our method to multi-turn dialogue scenarios. For each round of conversation, you can simply repeat the method delineated in our paper and get the accurate response. This iterative applicability underscores the robustness and adaptability of our method in dynamic conversational contexts.

- **Benchmarks on multiple rounds of conversation?**

We conducted experiments on benchmarks shown in LLaVA paper to demonstrate the effectiveness of our method, so currently we haven't test our model on this kind of benchmark. But as stated above, our method can be migrated easily for multiple rounds of conversation, so evaluations on this kind of benchmark are indeed an interesting topic.

- **Multiple ROI for multiple objects?**

Our approach aims at identifying the ROI corresponding to the input questions. As shown in our paper, we get the ROI based on a score threshold. If the question is about multiple objects in the image, the ROI should contain all the objects or the most important object relevant to the queries.

- **Failure cases?**

In future work, we plan to include an analysis of failure cases. In short, the failure cases mainly comes from two scenarios as we observed: 

- Given the inherent ambiguity in the semantics of certain queries, our method may occasionally falter. 
- There still exists some questions that are not relevant to a specific region but should consider the whole image. In this case, our method may fail to improve the performance.

However, statistically, the comprehensive enhancements observed across all benchmarks demonstrate the superiority of our approach in comparison to baseline models. Moreover, considering that our method preserves the integrity of the raw input images, it is reasonable that Chain-of-Spot would not reduce the performance of baseline models.

**Comment by hhaAndroid** [comment]
@liuzuyan Thank you
