### ISSUE TITLE
Compare to Chatspot.

### ISSUE THREAD

**Issue by Ucas-HaoranWei** [dongyh20/Chain-of-Spot#3]
I read the Chain-of-Spot paper which is very similar to Chatspot. 
I want to know their differences and why you do not cite [Chatspot](https://arxiv.org/pdf/2307.09474.pdf)？
Thanks

**Comment by liuzuyan** [comment]
Thanks for your interest in our work. We apologize that we did not take notice of ChatsSpot before, but after a careful reading and profound discussion among our group, we think that there exist significant differences between these two works, considering the motivation and the implementation of both methods. We would like to share our opinions below for further discussion.
1) Indeed, both works demonstrate that the ROI of the input image is crucial for visual understanding. However, Chain-of-Spot takes inspiration from Chain-of-Thought, which can improve the reasoning skill of LLMs by illustrating the thought process. Here, ROI is introduced as an intermediate result of the reasoning process of VLMs themselves to improve their reasoning skills. In contrast, ChatSpot takes the users' requirements into consideration and leverages the additional information from users to achieve better reasoning performance.
2) The implementation of these two works further reflects the different targets of both works. Chain-of-Spot enables VLMs to generate ROI customized for each input query automatically. To achieve this, we also formed a systematical method to generate training data. While our method aims at solving each query in a self-motivated way, we noticed that ChatSpot utilizes user-level conversations and allows users to point out a specific region as assistant information. Therefore, the two methods hold different targets to solve and result in different implementations, which is also clearly shown in the experiment section.

Summarily, we do not think that Chain-of-Spot is similar to ChatSpot in terms of motivation and methodology. However, we still would like to proofread our paper and discuss all the region-based methods in our revised version for a comprehensive understanding of these approaches. We are also open to any further discussions should you want.
