### ISSUE TITLE
What does the params in chain-of-spot.json mean？

### ISSUE THREAD

**Issue by echo840** [dongyh20/Chain-of-Spot#7]
![image](https://github.com/dongyh20/Chain-of-Spot/assets/87795401/8bb50245-f697-4087-b147-3f4dd672c06b)
Why not directly use the coordinates of the top-left and bottom-right corners to represent it?

**Comment by dongyh20** [comment]
Thanks for your interest in our work. The params in our data represent the top-left coordinate and the length of the bounding box respectively. As we found that square bounding box is already enough for CoS, so we collect our data in this format. Note that the bounding box should always within the image, we implement this in our [code](https://github.com/dongyh20/Chain-of-Spot/blob/429335a742197e6f88efdecf7c56a3e879be45d2/llava/train/train_CoS.py#L723).
